# -*- coding: utf-8 -*-
"""RenyiEntropy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aaVNthZ01DhU6HgwyK_QQurZh1BmbMfW
"""

import numpy as np

def renyi(tx,fx,z):
  alpha = 3

  dt=tx[1]-tx[0]
  df=fx[1]-fx[0]
  z2=np.abs(z)**2

  smod = sum(sum(z2))
  s3 = sum(sum((z2/smod)**alpha))
  
  ren = np.log2(s3)/(1-alpha) + np.log2(dt*df)
  return ren